# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Liveemcasa' do
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!


pod 'Moya/RxSwift', '~> 14.0'
pod 'Moya-ModelMapper', '~> 10.0'
pod 'SDWebImage', '~> 5.0'
pod 'Firebase/Analytics'

end
